name: Build and Publish Docs
on:
  push:
    branches: [ '**' ]

  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build for SF ${{ matrix.symfony }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        symfony: ['4.4', '5.2', '5.x']

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          path: symfony-docs

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: docker-cache-${{ matrix.symfony }}
          restore-keys: |
            docker-cache-

      - uses: actions/cache@v2
        with:
          path: symfony-docs/output
          key: ${{ runner.os }}

      - name: Build Docker Image
        working-directory: symfony-docs
        run: |
          docker build --tag=symfony-docs-builder --build-arg BRANCH=${{ matrix.symfony }} .
          mkdir -p output/${{ matrix.symfony }}

      - name: Build Epub
        working-directory: symfony-docs
        run: |
          docker run --rm -v "${PWD}/output/${{ matrix.symfony }}:/output" --user="$(id -u):$(id -g)" symfony-docs-builder epub

      - name: Build HTML
        working-directory: symfony-docs
        run: |
          docker run --rm -v "${PWD}/output/${{ matrix.symfony }}:/output" --user="$(id -u):$(id -g)" symfony-docs-builder html

      - name: Prepare artifacts
        working-directory: symfony-docs
        run: |
          mv output/${{ matrix.symfony }}/epub/SymfonyFrameworkDocumentation.epub output/${{ matrix.symfony }}/docs.epub

      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.symfony }}
          path: |
            symfony-docs/output/${{ matrix.symfony }}
            !symfony-docs/output/${{ matrix.symfony }}/doctrees
            !symfony-docs/output/${{ matrix.symfony }}/epub

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          repository: wyster/wyster.github.io
          persist-credentials: false
          path: github-io

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: github-io/symfony-docs

      - name: Commit changes
        working-directory: github-io
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Generate docs for SF"

      - name: Push changes to github.io
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SECRET_TOKEN }}
          branch: main
          repository: wyster/wyster.github.io
          directory: github-io
